local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 1.0
    global_frame: odom
    robot_base_frame: base_link
    use_sim_time: true
    rolling_window: true
    width: 10.0
    height: 10.0
    resolution: 0.05
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: depth_camera

      depth_camera:
        topic: /camera/depth/points
        sensor_frame: camera_link_optical
        data_type: PointCloud2
        expected_update_rate: 0.5
        min_obstacle_height: 0.0
        max_obstacle_height: 2.0
        obstacle_range: 2.5
        raytrace_range: 3.0
        marking: true
        clearing: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true
      inflation_radius: 0.5
